---
language: python
python: "3.5"

# Use the new container infrastructure
sudo: false

# Install pip
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible
  # Check ansible version
  - ansible --version
  - ansible-galaxy install -r test/requirements.yml -p test/roles/

script:
  # Basic role syntax check
  - ansible-playbook test/main.yml -i test/hosts --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
